// Generated from poe.ninja ids + poe2db.kr names.
export const NAMES: Record<string, string> = {
  "alch": "연금술의 오브",
  "orb-of-alchemy": "연금술의 오브",
  "orbofalchemy": "연금술의 오브",
  "exalted": "엑잘티드 오브",
  "exalted-orb": "엑잘티드 오브",
  "exaltedorb": "엑잘티드 오브",
  "ancient-infuser": "고대 주입기",
  "ancientinfuser": "고대 주입기",
  "chaos": "카오스 오브",
  "chaos-orb": "카오스 오브",
  "chaosorb": "카오스 오브",
  "divine": "신성한 오브",
  "divine-orb": "신성한 오브",
  "divineorb": "신성한 오브",
  "annul": "소멸의 오브",
  "orb-of-annulment": "소멸의 오브",
  "orbofannulment": "소멸의 오브",
  "architects-orb": "건축가의 오브",
  "architectsorb": "건축가의 오브",
  "artificers": "숙련공의 오브",
  "artificers-orb": "숙련공의 오브",
  "artificersorb": "숙련공의 오브",
  "aug": "확장의 오브",
  "orb-of-augmentation": "확장의 오브",
  "orbofaugmentation": "확장의 오브",
  "bauble": "유리직공의 방울",
  "glassblowers-bauble": "유리직공의 방울",
  "glassblowersbauble": "유리직공의 방울",
  "chance": "기회의 오브",
  "orb-of-chance": "기회의 오브",
  "orbofchance": "기회의 오브",
  "chance-shard": "기회의 파편",
  "chanceshard": "기회의 파편",
  "core-destabiliser": "핵 불안정화기",
  "coredestabiliser": "핵 불안정화기",
  "crystallised-corruption": "결정화된 타락",
  "crystallisedcorruption": "결정화된 타락",
  "etcher": "신비학자의 식각기",
  "arcanists-etcher": "신비학자의 식각기",
  "arcanistsetcher": "신비학자의 식각기",
  "fracturing-orb": "분열의 오브",
  "fracturingorb": "분열의 오브",
  "greater-regal-orb": "상위 제왕의 오브",
  "greaterregalorb": "상위 제왕의 오브",
  "kopecs-orb-of-sacrifice": "코펙의 희생의 오브",
  "kopecsorbofsacrifice": "코펙의 희생의 오브",
  "lesser-jewellers-orb": "하위 쥬얼러 오브",
  "lesserjewellersorb": "하위 쥬얼러 오브",
  "perfect-chaos-orb": "완벽한 카오스 오브",
  "perfectchaosorb": "완벽한 카오스 오브",
  "perfect-exalted-orb": "완벽한 엑잘티드 오브",
  "perfectexaltedorb": "완벽한 엑잘티드 오브",
  "perfect-jewellers-orb": "완벽한 쥬얼러 오브",
  "perfectjewellersorb": "완벽한 쥬얼러 오브",
  "perfect-regal-orb": "완벽한 제왕의 오브",
  "perfectregalorb": "완벽한 제왕의 오브",
  "regal": "제왕의 오브",
  "regal-orb": "제왕의 오브",
  "regalorb": "제왕의 오브",
  "scrap": "방어구 장인의 고철",
  "armourers-scrap": "방어구 장인의 고철",
  "armourersscrap": "방어구 장인의 고철",
  "vaal-arcanists-infuser": "바알 신비학자의 주입기",
  "vaalarcanistsinfuser": "바알 신비학자의 주입기",
  "vaal-armourers-infuser": "바알 방어구 장인의 주입기",
  "vaalarmourersinfuser": "바알 방어구 장인의 주입기",
  "vaal-blacksmiths-infuser": "바알 대장장이의 주입기",
  "vaalblacksmithsinfuser": "바알 대장장이의 주입기",
  "vaal-cultivation-orb": "바알 함양 오브",
  "vaalcultivationorb": "바알 함양 오브",
  "vaal-siphoner": "바알 착취기",
  "vaalsiphoner": "바알 착취기",
  "cryptic-key": "난해한 열쇠",
  "cryptickey": "난해한 열쇠",
  "hinekoras-lock": "히네코라의 머리카락",
  "hinekoraslock": "히네코라의 머리카락",
  "artificers-shard": "숙련공의 파편",
  "artificersshard": "숙련공의 파편",
  "gcp": "세공사의 프리즘",
  "gemcutters-prism": "세공사의 프리즘",
  "gemcuttersprism": "세공사의 프리즘",
  "greater-chaos-orb": "상위 카오스 오브",
  "greaterchaosorb": "상위 카오스 오브",
  "greater-exalted-orb": "상위 엑잘티드 오브",
  "greaterexaltedorb": "상위 엑잘티드 오브",
  "greater-jewellers-orb": "상위 쥬얼러 오브",
  "greaterjewellersorb": "상위 쥬얼러 오브",
  "greater-orb-of-augmentation": "상위 확장의 오브",
  "greaterorbofaugmentation": "상위 확장의 오브",
  "greater-orb-of-transmutation": "상위 진화의 오브",
  "greaterorboftransmutation": "상위 진화의 오브",
  "kamasas-orb-of-sacrifice": "카마사의 희생의 오브",
  "kamasasorbofsacrifice": "카마사의 희생의 오브",
  "mirror": "칼란드라의 거울",
  "mirror-of-kalandra": "칼란드라의 거울",
  "mirrorofkalandra": "칼란드라의 거울",
  "orb-of-extraction": "추출의 오브",
  "orbofextraction": "추출의 오브",
  "perfect-orb-of-augmentation": "완벽한 확장의 오브",
  "perfectorbofaugmentation": "완벽한 확장의 오브",
  "perfect-orb-of-transmutation": "완벽한 진화의 오브",
  "perfectorboftransmutation": "완벽한 진화의 오브",
  "transmutation-shard": "진화의 파편",
  "transmutationshard": "진화의 파편",
  "transmute": "진화의 오브",
  "orb-of-transmutation": "진화의 오브",
  "orboftransmutation": "진화의 오브",
  "vaal-catalysing-infuser": "바알 촉진시키는 주입기",
  "vaalcatalysinginfuser": "바알 촉진시키는 주입기",
  "vaal": "바알 오브",
  "vaal-orb": "바알 오브",
  "vaalorb": "바알 오브",
  "whetstone": "대장장이의 숫돌",
  "blacksmiths-whetstone": "대장장이의 숫돌",
  "blacksmithswhetstone": "대장장이의 숫돌",
  "wisdom": "감정 주문서",
  "scroll-of-wisdom": "감정 주문서",
  "scrollofwisdom": "감정 주문서",
  "yaomacs-orb-of-sacrifice": "야오맥의 희생의 오브",
  "yaomacsorbofsacrifice": "야오맥의 희생의 오브",
  "yuguls-orb-of-sacrifice": "유굴의 희생의 오브",
  "yugulsorbofsacrifice": "유굴의 희생의 오브",
  "azmeri-reliquary-key": "아즈메리 성유물 보관실 열쇠",
  "azmerireliquarykey": "아즈메리 성유물 보관실 열쇠",
  "breachlord-sac": "균열 군주 낭",
  "breachlordsac": "균열 군주 낭",
  "call-of-the-shadows": "그림자의 부름",
  "calloftheshadows": "그림자의 부름",
  "ancient-crisis-fragment": "고대 위기 조각",
  "ancientcrisisfragment": "고대 위기 조각",
  "cowardly-fate": "비겁한 운명",
  "cowardlyfate": "비겁한 운명",
  "deadly-fate": "치명적인 운명",
  "deadlyfate": "치명적인 운명",
  "faded-crisis-fragment": "빛바랜 위기 조각",
  "fadedcrisisfragment": "빛바랜 위기 조각",
  "kulemaks-invitation": "쿨레막의 초대",
  "kulemaksinvitation": "쿨레막의 초대",
  "olroths-reliquary-key": "올로스의 성유물 보관실 열쇠",
  "olrothsreliquarykey": "올로스의 성유물 보관실 열쇠",
  "origin-cradle": "기원 요람",
  "origincradle": "기원 요람",
  "ravens-reflection": "큰까마귀의 투영",
  "ravensreflection": "큰까마귀의 투영",
  "simulacrum": "복제된 영토",
  "tangmazus-reliquary-key": "탕마주의 성유물 보관실 열쇠",
  "tangmazusreliquarykey": "탕마주의 성유물 보관실 열쇠",
  "the-triskelion-reforged": "재련된 트리스켈리온",
  "thetriskelionreforged": "재련된 트리스켈리온",
  "twilight-reliquary-key": "황혼 성유물 보관실 열쇠",
  "twilightreliquarykey": "황혼 성유물 보관실 열쇠",
  "against-the-darkness": "자로크의 성유물 보관실 열쇠: 어둠 저항",
  "zarokhs-reliquary-key:-against-the-darkness": "자로크의 성유물 보관실 열쇠: 어둠 저항",
  "zarokhsreliquarykeyagainstthedarkness": "자로크의 성유물 보관실 열쇠: 어둠 저항",
  "origin-core": "기원 핵",
  "origincore": "기원 핵",
  "origin-spark": "기원 전기불꽃",
  "originspark": "기원 전기불꽃",
  "ritualistic-reliquary-key": "의식의 성유물 보관실 열쇠",
  "ritualisticreliquarykey": "의식의 성유물 보관실 열쇠",
  "shattered-triskelion": "산산이 조각난 트리스켈리온",
  "shatteredtriskelion": "산산이 조각난 트리스켈리온",
  "simulacrum-splinter": "복제된 영토 파편",
  "simulacrumsplinter": "복제된 영토 파편",
  "the-arbiters-reliquary-key": "중재자의 성유물 보관실 열쇠",
  "thearbitersreliquarykey": "중재자의 성유물 보관실 열쇠",
  "the-trialmasters-reliquary-key": "시련의 대가의 성유물 보관실 열쇠",
  "thetrialmastersreliquarykey": "시련의 대가의 성유물 보관실 열쇠",
  "victorious-fate": "승리의 운명",
  "victoriousfate": "승리의 운명",
  "weathered-crisis-fragment": "풍화된 위기 조각",
  "weatheredcrisisfragment": "풍화된 위기 조각",
  "xeshts-reliquary-key": "제쉬트의 성유물 보관실 열쇠",
  "xeshtsreliquarykey": "제쉬트의 성유물 보관실 열쇠",
  "an-audience-with-the-king": "왕 알현",
  "anaudiencewiththeking": "왕 알현",
  "omen-of-abyssal-echoes": "심연의 메아리의 징조",
  "omenofabyssalechoes": "심연의 메아리의 징조",
  "omen-of-answered-prayers": "응답받은 기도의 징조",
  "omenofansweredprayers": "응답받은 기도의 징조",
  "omen-of-chance": "기회의 징조",
  "omenofchance": "기회의 징조",
  "omen-of-chaotic-quantity": "혼란스러운 수량의 징조",
  "omenofchaoticquantity": "혼란스러운 수량의 징조",
  "omen-of-dextral-annulment": "우측 소멸의 징조",
  "omenofdextralannulment": "우측 소멸의 징조",
  "omen-of-dextral-crystallisation": "우측 결정화의 징조",
  "omenofdextralcrystallisation": "우측 결정화의 징조",
  "omen-of-dextral-erasure": "우측 말소의 징조",
  "omenofdextralerasure": "우측 말소의 징조",
  "omen-of-gambling": "도박의 징조",
  "omenofgambling": "도박의 징조",
  "omen-of-greater-exaltation": "상위 찬미의 징조",
  "omenofgreaterexaltation": "상위 찬미의 징조",
  "omen-of-light": "빛의 징조",
  "omenoflight": "빛의 징조",
  "omen-of-refreshment": "원기 회복의 징조",
  "omenofrefreshment": "원기 회복의 징조",
  "omen-of-reinforcements": "보강의 징조",
  "omenofreinforcements": "보강의 징조",
  "omen-of-secret-compartments": "비밀 공간의 징조",
  "omenofsecretcompartments": "비밀 공간의 징조",
  "omen-of-sinistral-annulment": "좌측 소멸의 징조",
  "omenofsinistralannulment": "좌측 소멸의 징조",
  "omen-of-sinistral-crystallisation": "좌측 결정화의 징조",
  "omenofsinistralcrystallisation": "좌측 결정화의 징조",
  "omen-of-sinistral-exaltation": "좌측 찬미의 징조",
  "omenofsinistralexaltation": "좌측 찬미의 징조",
  "omen-of-sinistral-necromancy": "좌측 강령술의 징조",
  "omenofsinistralnecromancy": "좌측 강령술의 징조",
  "omen-of-the-hunt": "사냥의 징조",
  "omenofthehunt": "사냥의 징조",
  "omen-of-the-liege": "군왕의 징조",
  "omenoftheliege": "군왕의 징조",
  "sacred-bloom": "신성한 꽃",
  "sacredbloom": "신성한 꽃",
  "head-of-the-king": "왕의 머리",
  "headoftheking": "왕의 머리",
  "omen-of-amelioration": "개량의 징조",
  "omenofamelioration": "개량의 징조",
  "omen-of-bartering": "물물교환의 징조",
  "omenofbartering": "물물교환의 징조",
  "omen-of-catalysing-exaltation": "촉진하는 찬미의 징조",
  "omenofcatalysingexaltation": "촉진하는 찬미의 징조",
  "omen-of-chaotic-effectiveness": "혼란스러운 효율의 징조",
  "omenofchaoticeffectiveness": "혼란스러운 효율의 징조",
  "omen-of-chaotic-monsters": "혼란스러운 괴물의 징조",
  "omenofchaoticmonsters": "혼란스러운 괴물의 징조",
  "omen-of-chaotic-rarity": "혼란스러운 희귀도의 징조",
  "omenofchaoticrarity": "혼란스러운 희귀도의 징조",
  "omen-of-dextral-exaltation": "우측 찬미의 징조",
  "omenofdextralexaltation": "우측 찬미의 징조",
  "omen-of-dextral-necromancy": "우측 강령술의 징조",
  "omenofdextralnecromancy": "우측 강령술의 징조",
  "omen-of-putrefaction": "부패의 징조",
  "omenofputrefaction": "부패의 징조",
  "omen-of-resurgence": "재기의 징조",
  "omenofresurgence": "재기의 징조",
  "omen-of-sanctification": "축성의 징조",
  "omenofsanctification": "축성의 징조",
  "omen-of-sinistral-erasure": "좌측 말소의 징조",
  "omenofsinistralerasure": "좌측 말소의 징조",
  "omen-of-the-ancients": "고대인의 징조",
  "omenoftheancients": "고대인의 징조",
  "omen-of-the-blackblooded": "검은 피의 징조",
  "omenoftheblackblooded": "검은 피의 징조",
  "omen-of-the-blessed": "축복받은 자의 징조",
  "omenoftheblessed": "축복받은 자의 징조",
  "omen-of-the-sovereign": "군주의 징조",
  "omenofthesovereign": "군주의 징조",
  "omen-of-whittling": "절사의 징조",
  "omenofwhittling": "절사의 징조",
  "essence-of-delirium": "섬망의 에센스",
  "essenceofdelirium": "섬망의 에센스",
  "essence-of-sorcery": "마술의 에센스",
  "essenceofsorcery": "마술의 에센스",
  "essence-of-the-breach": "균열의 에센스",
  "essenceofthebreach": "균열의 에센스",
  "greater-essence-of-alacrity": "상위 기민성의 에센스",
  "greateressenceofalacrity": "상위 기민성의 에센스",
  "greater-essence-of-command": "상위 지휘의 에센스",
  "greateressenceofcommand": "상위 지휘의 에센스",
  "greater-essence-of-enhancement": "상위 강화의 에센스",
  "greateressenceofenhancement": "상위 강화의 에센스",
  "greater-essence-of-flames": "상위 화염의 에센스",
  "greateressenceofflames": "상위 화염의 에센스",
  "greater-essence-of-grounding": "상위 접지의 에센스",
  "greateressenceofgrounding": "상위 접지의 에센스",
  "greater-essence-of-insulation": "상위 절연의 에센스",
  "greateressenceofinsulation": "상위 절연의 에센스",
  "greater-essence-of-opulence": "상위 풍요의 에센스",
  "greateressenceofopulence": "상위 풍요의 에센스",
  "greater-essence-of-ruin": "상위 폐허의 에센스",
  "greateressenceofruin": "상위 폐허의 에센스",
  "greater-essence-of-sorcery": "상위 마술의 에센스",
  "greateressenceofsorcery": "상위 마술의 에센스",
  "greater-essence-of-the-body": "상위 육신의 에센스",
  "greateressenceofthebody": "상위 육신의 에센스",
  "perfect-essence-of-abrasion": "완벽한 마모의 에센스",
  "perfectessenceofabrasion": "완벽한 마모의 에센스",
  "perfect-essence-of-alacrity": "완벽한 기민성의 에센스",
  "perfectessenceofalacrity": "완벽한 기민성의 에센스",
  "perfect-essence-of-battle": "완벽한 전투의 에센스",
  "perfectessenceofbattle": "완벽한 전투의 에센스",
  "perfect-essence-of-command": "완벽한 지휘의 에센스",
  "perfectessenceofcommand": "완벽한 지휘의 에센스",
  "perfect-essence-of-electricity": "완벽한 전기의 에센스",
  "perfectessenceofelectricity": "완벽한 전기의 에센스",
  "perfect-essence-of-enhancement": "완벽한 강화의 에센스",
  "perfectessenceofenhancement": "완벽한 강화의 에센스",
  "perfect-essence-of-haste": "완벽한 가속의 에센스",
  "perfectessenceofhaste": "완벽한 가속의 에센스",
  "perfect-essence-of-opulence": "완벽한 풍요의 에센스",
  "perfectessenceofopulence": "완벽한 풍요의 에센스",
  "perfect-essence-of-thawing": "완벽한 해동의 에센스",
  "perfectessenceofthawing": "완벽한 해동의 에센스",
  "perfect-essence-of-the-body": "완벽한 육신의 에센스",
  "perfectessenceofthebody": "완벽한 육신의 에센스",
  "perfect-essence-of-the-infinite": "완벽한 무한의 에센스",
  "perfectessenceoftheinfinite": "완벽한 무한의 에센스",
  "essence-of-abrasion": "마모의 에센스",
  "essenceofabrasion": "마모의 에센스",
  "essence-of-alacrity": "기민성의 에센스",
  "essenceofalacrity": "기민성의 에센스",
  "essence-of-command": "지휘의 에센스",
  "essenceofcommand": "지휘의 에센스",
  "essence-of-flames": "화염의 에센스",
  "essenceofflames": "화염의 에센스",
  "essence-of-grounding": "접지의 에센스",
  "essenceofgrounding": "접지의 에센스",
  "essence-of-haste": "가속의 에센스",
  "essenceofhaste": "가속의 에센스",
  "essence-of-horror": "경악의 에센스",
  "essenceofhorror": "경악의 에센스",
  "essence-of-hysteria": "발작의 에센스",
  "essenceofhysteria": "발작의 에센스",
  "essence-of-ice": "얼음의 에센스",
  "essenceofice": "얼음의 에센스",
  "essence-of-insanity": "광기의 에센스",
  "essenceofinsanity": "광기의 에센스",
  "essence-of-insulation": "절연의 에센스",
  "essenceofinsulation": "절연의 에센스",
  "essence-of-opulence": "풍요의 에센스",
  "essenceofopulence": "풍요의 에센스",
  "essence-of-seeking": "추구의 에센스",
  "essenceofseeking": "추구의 에센스",
  "essence-of-thawing": "해동의 에센스",
  "essenceofthawing": "해동의 에센스",
  "essence-of-the-abyss": "심연의 에센스",
  "essenceoftheabyss": "심연의 에센스",
  "essence-of-the-body": "육신의 에센스",
  "essenceofthebody": "육신의 에센스",
  "essence-of-the-infinite": "무한의 에센스",
  "essenceoftheinfinite": "무한의 에센스",
  "essence-of-battle": "전투의 에센스",
  "essenceofbattle": "전투의 에센스",
  "essence-of-electricity": "전기의 에센스",
  "essenceofelectricity": "전기의 에센스",
  "essence-of-enhancement": "강화의 에센스",
  "essenceofenhancement": "강화의 에센스",
  "essence-of-ruin": "폐허의 에센스",
  "essenceofruin": "폐허의 에센스",
  "greater-essence-of-ice": "상위 얼음의 에센스",
  "greateressenceofice": "상위 얼음의 에센스",
  "lesser-essence-of-opulence": "하위 풍요의 에센스",
  "lesseressenceofopulence": "하위 풍요의 에센스",
  "greater-essence-of-abrasion": "상위 마모의 에센스",
  "greateressenceofabrasion": "상위 마모의 에센스",
  "greater-essence-of-battle": "상위 전투의 에센스",
  "greateressenceofbattle": "상위 전투의 에센스",
  "greater-essence-of-electricity": "상위 전기의 에센스",
  "greateressenceofelectricity": "상위 전기의 에센스",
  "greater-essence-of-haste": "상위 가속의 에센스",
  "greateressenceofhaste": "상위 가속의 에센스",
  "greater-essence-of-seeking": "상위 추구의 에센스",
  "greateressenceofseeking": "상위 추구의 에센스",
  "greater-essence-of-thawing": "상위 해동의 에센스",
  "greateressenceofthawing": "상위 해동의 에센스",
  "greater-essence-of-the-infinite": "상위 무한의 에센스",
  "greateressenceoftheinfinite": "상위 무한의 에센스",
  "greater-essence-of-the-mind": "상위 정신의 에센스",
  "greateressenceofthemind": "상위 정신의 에센스",
  "lesser-essence-of-abrasion": "하위 마모의 에센스",
  "lesseressenceofabrasion": "하위 마모의 에센스",
  "lesser-essence-of-command": "하위 지휘의 에센스",
  "lesseressenceofcommand": "하위 지휘의 에센스",
  "lesser-essence-of-electricity": "하위 전기의 에센스",
  "lesseressenceofelectricity": "하위 전기의 에센스",
  "lesser-essence-of-enhancement": "하위 강화의 에센스",
  "lesseressenceofenhancement": "하위 강화의 에센스",
  "lesser-essence-of-grounding": "하위 접지의 에센스",
  "lesseressenceofgrounding": "하위 접지의 에센스",
  "lesser-essence-of-haste": "하위 가속의 에센스",
  "lesseressenceofhaste": "하위 가속의 에센스",
  "lesser-essence-of-ice": "하위 얼음의 에센스",
  "lesseressenceofice": "하위 얼음의 에센스",
  "lesser-essence-of-insulation": "하위 절연의 에센스",
  "lesseressenceofinsulation": "하위 절연의 에센스",
  "lesser-essence-of-sorcery": "하위 마술의 에센스",
  "lesseressenceofsorcery": "하위 마술의 에센스",
  "lesser-essence-of-thawing": "하위 해동의 에센스",
  "lesseressenceofthawing": "하위 해동의 에센스",
  "lesser-essence-of-the-body": "하위 육신의 에센스",
  "lesseressenceofthebody": "하위 육신의 에센스",
  "perfect-essence-of-flames": "완벽한 화염의 에센스",
  "perfectessenceofflames": "완벽한 화염의 에센스",
  "perfect-essence-of-grounding": "완벽한 접지의 에센스",
  "perfectessenceofgrounding": "완벽한 접지의 에센스",
  "perfect-essence-of-ice": "완벽한 얼음의 에센스",
  "perfectessenceofice": "완벽한 얼음의 에센스",
  "perfect-essence-of-insulation": "완벽한 절연의 에센스",
  "perfectessenceofinsulation": "완벽한 절연의 에센스",
  "perfect-essence-of-ruin": "완벽한 폐허의 에센스",
  "perfectessenceofruin": "완벽한 폐허의 에센스",
  "perfect-essence-of-seeking": "완벽한 추구의 에센스",
  "perfectessenceofseeking": "완벽한 추구의 에센스",
  "perfect-essence-of-sorcery": "완벽한 마술의 에센스",
  "perfectessenceofsorcery": "완벽한 마술의 에센스",
  "perfect-essence-of-the-mind": "완벽한 정신의 에센스",
  "perfectessenceofthemind": "완벽한 정신의 에센스",
  "uncut-skill-gem-12": "미가공 스킬 젬 (12레벨)",
  "uncut-skill-gem-level-12": "미가공 스킬 젬 (12레벨)",
  "uncutskillgemlevel12": "미가공 스킬 젬 (12레벨)",
  "uncut-skill-gem-14": "미가공 스킬 젬 (14레벨)",
  "uncut-skill-gem-level-14": "미가공 스킬 젬 (14레벨)",
  "uncutskillgemlevel14": "미가공 스킬 젬 (14레벨)",
  "uncut-skill-gem-15": "미가공 스킬 젬 (15레벨)",
  "uncut-skill-gem-level-15": "미가공 스킬 젬 (15레벨)",
  "uncutskillgemlevel15": "미가공 스킬 젬 (15레벨)",
  "uncut-skill-gem-17": "미가공 스킬 젬 (17레벨)",
  "uncut-skill-gem-level-17": "미가공 스킬 젬 (17레벨)",
  "uncutskillgemlevel17": "미가공 스킬 젬 (17레벨)",
  "uncut-skill-gem-19": "미가공 스킬 젬 (19레벨)",
  "uncut-skill-gem-level-19": "미가공 스킬 젬 (19레벨)",
  "uncutskillgemlevel19": "미가공 스킬 젬 (19레벨)",
  "uncut-skill-gem-5": "미가공 스킬 젬 (5레벨)",
  "uncut-skill-gem-level-5": "미가공 스킬 젬 (5레벨)",
  "uncutskillgemlevel5": "미가공 스킬 젬 (5레벨)",
  "uncut-skill-gem-6": "미가공 스킬 젬 (6레벨)",
  "uncut-skill-gem-level-6": "미가공 스킬 젬 (6레벨)",
  "uncutskillgemlevel6": "미가공 스킬 젬 (6레벨)",
  "uncut-skill-gem-7": "미가공 스킬 젬 (7레벨)",
  "uncut-skill-gem-level-7": "미가공 스킬 젬 (7레벨)",
  "uncutskillgemlevel7": "미가공 스킬 젬 (7레벨)",
  "uncut-skill-gem-8": "미가공 스킬 젬 (8레벨)",
  "uncut-skill-gem-level-8": "미가공 스킬 젬 (8레벨)",
  "uncutskillgemlevel8": "미가공 스킬 젬 (8레벨)",
  "uncut-skill-gem-9": "미가공 스킬 젬 (9레벨)",
  "uncut-skill-gem-level-9": "미가공 스킬 젬 (9레벨)",
  "uncutskillgemlevel9": "미가공 스킬 젬 (9레벨)",
  "uncut-spirit-gem-12": "미가공 정신력 젬 (12레벨)",
  "uncut-spirit-gem-level-12": "미가공 정신력 젬 (12레벨)",
  "uncutspiritgemlevel12": "미가공 정신력 젬 (12레벨)",
  "uncut-spirit-gem-15": "미가공 정신력 젬 (15레벨)",
  "uncut-spirit-gem-level-15": "미가공 정신력 젬 (15레벨)",
  "uncutspiritgemlevel15": "미가공 정신력 젬 (15레벨)",
  "uncut-spirit-gem-18": "미가공 정신력 젬 (18레벨)",
  "uncut-spirit-gem-level-18": "미가공 정신력 젬 (18레벨)",
  "uncutspiritgemlevel18": "미가공 정신력 젬 (18레벨)",
  "uncut-spirit-gem-19": "미가공 정신력 젬 (19레벨)",
  "uncut-spirit-gem-level-19": "미가공 정신력 젬 (19레벨)",
  "uncutspiritgemlevel19": "미가공 정신력 젬 (19레벨)",
  "uncut-spirit-gem-4": "미가공 정신력 젬 (4레벨)",
  "uncut-spirit-gem-level-4": "미가공 정신력 젬 (4레벨)",
  "uncutspiritgemlevel4": "미가공 정신력 젬 (4레벨)",
  "uncut-spirit-gem-5": "미가공 정신력 젬 (5레벨)",
  "uncut-spirit-gem-level-5": "미가공 정신력 젬 (5레벨)",
  "uncutspiritgemlevel5": "미가공 정신력 젬 (5레벨)",
  "uncut-spirit-gem-6": "미가공 정신력 젬 (6레벨)",
  "uncut-spirit-gem-level-6": "미가공 정신력 젬 (6레벨)",
  "uncutspiritgemlevel6": "미가공 정신력 젬 (6레벨)",
  "uncut-skill-gem-10": "미가공 스킬 젬 (10레벨)",
  "uncut-skill-gem-level-10": "미가공 스킬 젬 (10레벨)",
  "uncutskillgemlevel10": "미가공 스킬 젬 (10레벨)",
  "uncut-skill-gem-11": "미가공 스킬 젬 (11레벨)",
  "uncut-skill-gem-level-11": "미가공 스킬 젬 (11레벨)",
  "uncutskillgemlevel11": "미가공 스킬 젬 (11레벨)",
  "uncut-skill-gem-13": "미가공 스킬 젬 (13레벨)",
  "uncut-skill-gem-level-13": "미가공 스킬 젬 (13레벨)",
  "uncutskillgemlevel13": "미가공 스킬 젬 (13레벨)",
  "uncut-skill-gem-16": "미가공 스킬 젬 (16레벨)",
  "uncut-skill-gem-level-16": "미가공 스킬 젬 (16레벨)",
  "uncutskillgemlevel16": "미가공 스킬 젬 (16레벨)",
  "uncut-skill-gem-18": "미가공 스킬 젬 (18레벨)",
  "uncut-skill-gem-level-18": "미가공 스킬 젬 (18레벨)",
  "uncutskillgemlevel18": "미가공 스킬 젬 (18레벨)",
  "uncut-skill-gem-1": "미가공 스킬 젬 (1레벨)",
  "uncut-skill-gem-level-1": "미가공 스킬 젬 (1레벨)",
  "uncutskillgemlevel1": "미가공 스킬 젬 (1레벨)",
  "uncut-skill-gem-20": "미가공 스킬 젬 (20레벨)",
  "uncut-skill-gem-level-20": "미가공 스킬 젬 (20레벨)",
  "uncutskillgemlevel20": "미가공 스킬 젬 (20레벨)",
  "uncut-skill-gem-2": "미가공 스킬 젬 (2레벨)",
  "uncut-skill-gem-level-2": "미가공 스킬 젬 (2레벨)",
  "uncutskillgemlevel2": "미가공 스킬 젬 (2레벨)",
  "uncut-skill-gem-3": "미가공 스킬 젬 (3레벨)",
  "uncut-skill-gem-level-3": "미가공 스킬 젬 (3레벨)",
  "uncutskillgemlevel3": "미가공 스킬 젬 (3레벨)",
  "uncut-skill-gem-4": "미가공 스킬 젬 (4레벨)",
  "uncut-skill-gem-level-4": "미가공 스킬 젬 (4레벨)",
  "uncutskillgemlevel4": "미가공 스킬 젬 (4레벨)",
  "uncut-spirit-gem-10": "미가공 정신력 젬 (10레벨)",
  "uncut-spirit-gem-level-10": "미가공 정신력 젬 (10레벨)",
  "uncutspiritgemlevel10": "미가공 정신력 젬 (10레벨)",
  "uncut-spirit-gem-11": "미가공 정신력 젬 (11레벨)",
  "uncut-spirit-gem-level-11": "미가공 정신력 젬 (11레벨)",
  "uncutspiritgemlevel11": "미가공 정신력 젬 (11레벨)",
  "uncut-spirit-gem-13": "미가공 정신력 젬 (13레벨)",
  "uncut-spirit-gem-level-13": "미가공 정신력 젬 (13레벨)",
  "uncutspiritgemlevel13": "미가공 정신력 젬 (13레벨)",
  "uncut-spirit-gem-14": "미가공 정신력 젬 (14레벨)",
  "uncut-spirit-gem-level-14": "미가공 정신력 젬 (14레벨)",
  "uncutspiritgemlevel14": "미가공 정신력 젬 (14레벨)",
  "uncut-spirit-gem-16": "미가공 정신력 젬 (16레벨)",
  "uncut-spirit-gem-level-16": "미가공 정신력 젬 (16레벨)",
  "uncutspiritgemlevel16": "미가공 정신력 젬 (16레벨)",
  "uncut-spirit-gem-17": "미가공 정신력 젬 (17레벨)",
  "uncut-spirit-gem-level-17": "미가공 정신력 젬 (17레벨)",
  "uncutspiritgemlevel17": "미가공 정신력 젬 (17레벨)",
  "uncut-spirit-gem-20": "미가공 정신력 젬 (20레벨)",
  "uncut-spirit-gem-level-20": "미가공 정신력 젬 (20레벨)",
  "uncutspiritgemlevel20": "미가공 정신력 젬 (20레벨)",
  "uncut-spirit-gem-7": "미가공 정신력 젬 (7레벨)",
  "uncut-spirit-gem-level-7": "미가공 정신력 젬 (7레벨)",
  "uncutspiritgemlevel7": "미가공 정신력 젬 (7레벨)",
  "uncut-spirit-gem-8": "미가공 정신력 젬 (8레벨)",
  "uncut-spirit-gem-level-8": "미가공 정신력 젬 (8레벨)",
  "uncutspiritgemlevel8": "미가공 정신력 젬 (8레벨)",
  "uncut-spirit-gem-9": "미가공 정신력 젬 (9레벨)",
  "uncut-spirit-gem-level-9": "미가공 정신력 젬 (9레벨)",
  "uncutspiritgemlevel9": "미가공 정신력 젬 (9레벨)",
  "uncut-support-gem-1": "미가공 보조 젬 (1레벨)",
  "uncut-support-gem-level-1": "미가공 보조 젬 (1레벨)",
  "uncutsupportgemlevel1": "미가공 보조 젬 (1레벨)",
  "uncut-support-gem-2": "미가공 보조 젬 (2레벨)",
  "uncut-support-gem-level-2": "미가공 보조 젬 (2레벨)",
  "uncutsupportgemlevel2": "미가공 보조 젬 (2레벨)",
  "uncut-support-gem-3": "미가공 보조 젬 (3레벨)",
  "uncut-support-gem-level-3": "미가공 보조 젬 (3레벨)",
  "uncutsupportgemlevel3": "미가공 보조 젬 (3레벨)",
  "uncut-support-gem-4": "미가공 보조 젬 (4레벨)",
  "uncut-support-gem-level-4": "미가공 보조 젬 (4레벨)",
  "uncutsupportgemlevel4": "미가공 보조 젬 (4레벨)",
  "uncut-support-gem-5": "미가공 보조 젬 (5레벨)",
  "uncut-support-gem-level-5": "미가공 보조 젬 (5레벨)",
  "uncutsupportgemlevel5": "미가공 보조 젬 (5레벨)",
  "ahns-citadel": "안의 성채",
  "ahnscitadel": "안의 성채",
  "ailiths-chimes": "아일리트의 종",
  "ailithschimes": "아일리트의 종",
  "amanamus-tithe": "아마나무의 십일조",
  "amanamustithe": "아마나무의 십일조",
  "arbiters-ignition": "중재자의 점화",
  "arbitersignition": "중재자의 점화",
  "arbiters-reach": "중재자의 역량",
  "arbitersreach": "중재자의 역량",
  "arjuns-medal": "아르준의 메달",
  "arjunsmedal": "아르준의 메달",
  "ataluis-bloodletting": "아탈루이의 사혈",
  "ataluisbloodletting": "아탈루이의 사혈",
  "atziris-allure": "앗지리의 매혹",
  "atzirisallure": "앗지리의 매혹",
  "atziris-impatience": "앗지리의 조바심",
  "atzirisimpatience": "앗지리의 조바심",
  "breachlords-amalgam": "균열 군주의 융합체",
  "breachlordsamalgam": "균열 군주의 융합체",
  "breachlords-rift": "균열 군주의 틈새",
  "breachlordsrift": "균열 군주의 틈새",
  "cathas-brilliance": "캐사의 광채",
  "cathasbrilliance": "캐사의 광채",
  "arakaalis-lust": "아라칼리의 욕망",
  "arakaalislust": "아라칼리의 욕망",
  "atziris-communion": "앗지리의 성찬식",
  "atziriscommunion": "앗지리의 성찬식",
  "bhatairs-vengeance": "바타이르의 복수",
  "bhatairsvengeance": "바타이르의 복수",
  "brutus-brain": "브루투스의 두뇌",
  "brutusbrain": "브루투스의 두뇌",
  "daressos-passion": "다레소의 열정",
  "daressospassion": "다레소의 열정",
  "dominus-grasp": "도미누스의 장악",
  "dominusgrasp": "도미누스의 장악",
  "eshs-prowess": "에쉬의 기량",
  "eshsprowess": "에쉬의 기량",
  "guatelitzis-ablation": "과텔리치의 삭마",
  "guatelitzisablation": "과텔리치의 삭마",
  "ixchels-torment": "익스첼의 고통",
  "ixchelstorment": "익스첼의 고통",
  "kalisas-crescendo": "칼리사의 크레센도",
  "kalisascrescendo": "칼리사의 크레센도",
  "kurgals-leash": "쿠르갈의 가죽끈",
  "kurgalsleash": "쿠르갈의 가죽끈",
  "medveds-felling": "메드베드의 살상",
  "medvedsfelling": "메드베드의 살상",
  "morganas-tempest": "모르가나의 폭풍",
  "morganastempest": "모르가나의 폭풍",
  "oisins-oath": "오이신의 서약",
  "oisnsoath": "오이신의 서약",
  "olroths-hubris": "올로스의 오만",
  "olrothshubris": "올로스의 오만",
  "paquates-pact": "파콰테의 맹약",
  "paquatespact": "파콰테의 맹약",
  "prototype-seventeen": "프로토타입 17호",
  "prototypeseventeen": "프로토타입 17호",
  "rakiatas-flow": "라키아타의 흐름",
  "rakiatasflow": "라키아타의 흐름",
  "rathas-assault": "라타의 공격",
  "rathasassault": "라타의 공격",
  "romiras-requital": "로미라의 보답",
  "romirasrequital": "로미라의 보답",
  "siones-temper": "시온의 성미",
  "sionestemper": "시온의 성미",
  "tangmazus-thurible": "탕마주의 향로",
  "tangmazusthurible": "탕마주의 향로",
  "tasalios-rhythm": "타살리오의 리듬",
  "tasaliosrhythm": "타살리오의 리듬",
  "tuls-avalanche": "툴의 산사태",
  "tulsavalanche": "툴의 산사태",
  "uhtreds-rite": "우트레드의 의례",
  "uhtredsrite": "우트레드의 의례",
  "varashtas-blessing": "바라시타의 축복",
  "varashtasblessing": "바라시타의 축복",
  "vilentas-propulsion": "바일렌타의 추진",
  "vilentaspropulsion": "바일렌타의 추진",
  "vruuns-aftermath": "브룬의 여파",
  "vruunsaftermath": "브룬의 여파",
  "xibaquas-rending": "지바콰의 분리",
  "xibaquasrending": "지바콰의 분리",
  "zarokhs-revolt": "자로크의 봉기",
  "zarokhsrevolt": "자로크의 봉기",
  "zerphis-infamy": "제르피의 악명",
  "zerphisinfamy": "제르피의 악명",
  "cirels-cultivation": "키렐의 함양",
  "cirelscultivation": "키렐의 함양",
  "diallas-desire": "디알라의 갈망",
  "diallasdesire": "디알라의 갈망",
  "garukhans-resolve": "가루칸의 투지",
  "garukhansresolve": "가루칸의 투지",
  "rigwalds-ferocity": "리그월드의 흉포함",
  "rigwaldsferocity": "리그월드의 흉포함",
  "seraphs-heart": "고위 천사의 심장",
  "seraphsheart": "고위 천사의 심장",
  "uhtreds-exodus": "우트레드의 탈출",
  "uhtredsexodus": "우트레드의 탈출",
  "uul-netols-embrace": "울네톨의 포옹",
  "uulnetolsembrace": "울네톨의 포옹",
  "xophs-pyre": "조프의 장작",
  "xophspyre": "조프의 장작",
  "doedres-undoing": "도이드리의 파멸",
  "doedresundoing": "도이드리의 파멸",
  "einhars-beastrite": "아인하르의 야수의식",
  "einharsbeastrite": "아인하르의 야수의식",
  "eonyrs-thunder": "에오니르의 천둥",
  "eonyrsthunder": "에오니르의 천둥",
  "eshs-radiance": "에쉬의 광휘",
  "eshsradiance": "에쉬의 광휘",
  "kulemaks-dominion": "쿨레막의 지배",
  "kulemaksdominion": "쿨레막의 지배",
  "hayoxis-fulmination": "하욕시의 뇌전",
  "hayoxisfulmination": "하욕시의 뇌전",
  "helbryms-hide": "헬브림의 가죽",
  "helbrymshide": "헬브림의 가죽",
  "her-declaration": "그녀의 선언",
  "herdeclaration": "그녀의 선언",
  "kaoms-madness": "카옴의 광기",
  "kaomsmadness": "카옴의 광기",
  "khatals-rejuvenation": "카탈의 회춘",
  "khatalsrejuvenation": "카탈의 회춘",
  "mórrigans-insight": "모리건의 통찰",
  "morrigans-insight": "모리건의 통찰",
  "mrrigansinsight": "모리건의 통찰",
  "olroths-conviction": "올로스의 신념",
  "olrothsconviction": "올로스의 신념",
  "tacatis-ire": "타카티의 진노",
  "tacatisire": "타카티의 진노",
  "tawhoas-tending": "타호아의 보살핌",
  "tawhoastending": "타호아의 보살핌",
  "tecrods-revenge": "테크로드의 복수",
  "tecrodsrevenge": "테크로드의 복수",
  "tricksters-shard": "협잡꾼의 파편",
  "trickstersshard": "협잡꾼의 파편",
  "tuls-stillness": "툴의 고요",
  "tulsstillness": "툴의 고요",
  "uhtreds-augury": "우트레드의 점술",
  "uhtredsaugury": "우트레드의 점술",
  "uhtreds-constellation": "우트레드의 별자리",
  "uhtredsconstellation": "우트레드의 별자리",
  "uhtreds-omen": "우트레드의 징조",
  "uhtredsomen": "우트레드의 징조",
  "uruks-smelting": "우루크의 제련",
  "urukssmelting": "우루크의 제련",
  "voranas-siege": "보라나의 공성",
  "voranassiege": "보라나의 공성",
  "vruuns-inevitability": "브룬의 필연",
  "vruunsinevitability": "브룬의 필연",
  "zarokhs-refrain": "자로크의 절제",
  "zarokhsrefrain": "자로크의 절제",
  "atmohuas-soul-core-of-retreat": "앗모후아의 후퇴의 영혼 핵",
  "atmohuassoulcoreofretreat": "앗모후아의 후퇴의 영혼 핵",
  "atziris-soul-core-of-alacrity": "앗지리의 기민성 영혼 핵",
  "atzirissoulcoreofalacrity": "앗지리의 기민성 영혼 핵",
  "atziris-soul-core-of-vitality": "앗지리의 활력 영혼 핵",
  "atzirissoulcoreofvitality": "앗지리의 활력 영혼 핵",
  "atziris-soul-core-of-devotion": "앗지리의 헌신 영혼 핵",
  "atzirissoulcoreofdevotion": "앗지리의 헌신 영혼 핵",
  "atziris-soul-core-of-inoculation": "앗지리의 접종 영혼 핵",
  "atzirissoulcoreofinoculation": "앗지리의 접종 영혼 핵",
  "cholotls-soul-core-of-war": "촐로틀의 전쟁의 영혼 핵",
  "cholotlssoulcoreofwar": "촐로틀의 전쟁의 영혼 핵",
  "citaqualotls-soul-core-of-foulness": "시타콰로틀의 부정의 영혼 핵",
  "citaqualotlssoulcoreoffoulness": "시타콰로틀의 부정의 영혼 핵",
  "citaqualotls-thesis": "시타콰로틀의 명제",
  "citaqualotlsthesis": "시타콰로틀의 명제",
  "guatelitzis-soul-core-of-endurance": "과텔리치의 인내의 영혼 핵",
  "guatelitzissoulcoreofendurance": "과텔리치의 인내의 영혼 핵",
  "guatelitzis-thesis": "과텔리치의 명제",
  "guatelitzisthesis": "과텔리치의 명제",
  "jiquanis-soul-core-of-abundance": "지콰니의 풍부 영혼 핵",
  "jiquanissoulcoreofabundance": "지콰니의 풍부 영혼 핵",
  "jiquanis-soul-core-of-automation": "지콰니의 자동화 영혼 핵",
  "jiquanissoulcoreofautomation": "지콰니의 자동화 영혼 핵",
  "jiquanis-soul-core-of-malediction": "지콰니의 악담 영혼 핵",
  "jiquanissoulcoreofmalediction": "지콰니의 악담 영혼 핵",
  "jiquanis-soul-core-of-munitions": "지콰니의 군수품 영혼 핵",
  "jiquanissoulcoreofmunitions": "지콰니의 군수품 영혼 핵",
  "jiquanis-soul-core-of-rallying": "지콰니의 재집결 영혼 핵",
  "jiquanissoulcoreofrallying": "지콰니의 재집결 영혼 핵",
  "quipolatls-soul-core-of-flow": "퀴폴라틀의 흐름의 영혼 핵",
  "quipolatlssoulcoreofflow": "퀴폴라틀의 흐름의 영혼 핵",
  "soul-core-of-azcapa": "아즈카파의 영혼 핵",
  "soulcoreofazcapa": "아즈카파의 영혼 핵",
  "soul-core-of-citaqualotl": "시타콰로틀의 영혼 핵",
  "soulcoreofcitaqualotl": "시타콰로틀의 영혼 핵",
  "soul-core-of-jiquani": "지콰니의 영혼 핵",
  "soulcoreofjiquani": "지콰니의 영혼 핵",
  "soul-core-of-opiloti": "오필로티의 영혼 핵",
  "soulcoreofopiloti": "오필로티의 영혼 핵",
  "soul-core-of-puhuarte": "푸후알테의 영혼 핵",
  "soulcoreofpuhuarte": "푸후알테의 영혼 핵",
  "soul-core-of-tacati": "타카티의 영혼 핵",
  "soulcoreoftacati": "타카티의 영혼 핵",
  "soul-core-of-ticaba": "티카바의 영혼 핵",
  "soulcoreofticaba": "티카바의 영혼 핵",
  "soul-core-of-topotante": "토포탄테의 영혼 핵",
  "soulcoreoftopotante": "토포탄테의 영혼 핵",
  "soul-core-of-zantipi": "잔티피의 영혼 핵",
  "soulcoreofzantipi": "잔티피의 영혼 핵",
  "topotantes-soul-core-of-dampening": "토포탄테의 완화의 영혼 핵",
  "topotantessoulcoreofdampening": "토포탄테의 완화의 영혼 핵",
  "xipocados-soul-core-of-dominion": "지포카도의 지배의 영혼 핵",
  "xipocadossoulcoreofdominion": "지포카도의 지배의 영혼 핵",
  "xopecs-soul-core-of-power": "조펙의 힘의 영혼 핵",
  "xopecssoulcoreofpower": "조펙의 힘의 영혼 핵",
  "jiquanis-soul-core-of-quaking": "지콰니의 진동 영혼 핵",
  "jiquanissoulcoreofquaking": "지콰니의 진동 영혼 핵",
  "estazuntis-soul-core-of-convalescence": "에스타준티의 요양의 영혼 핵",
  "estazuntissoulcoreofconvalescence": "에스타준티의 요양의 영혼 핵",
  "hayoxis-soul-core-of-heatproofing": "하욕시의 내열의 영혼 핵",
  "hayoxissoulcoreofheatproofing": "하욕시의 내열의 영혼 핵",
  "jiquanis-soul-core-of-radiance": "지콰니의 광휘 영혼 핵",
  "jiquanissoulcoreofradiance": "지콰니의 광휘 영혼 핵",
  "jiquanis-soul-core-of-rippling": "지콰니의 물결 영혼 핵",
  "jiquanissoulcoreofrippling": "지콰니의 물결 영혼 핵",
  "jiquanis-soul-core-of-severing": "지콰니의 단절 영혼 핵",
  "jiquanissoulcoreofsevering": "지콰니의 단절 영혼 핵",
  "jiquanis-soul-core-of-snares": "지콰니의 올가미 영혼 핵",
  "jiquanissoulcoreofsnares": "지콰니의 올가미 영혼 핵",
  "jiquanis-soul-core-of-squalls": "지콰니의 돌풍 영혼 핵",
  "jiquanissoulcoreofsqualls": "지콰니의 돌풍 영혼 핵",
  "jiquanis-soul-core-of-targeting": "지콰니의 대상 지정 영혼 핵",
  "jiquanissoulcoreoftargeting": "지콰니의 대상 지정 영혼 핵",
  "jiquanis-soul-core-of-thundering": "지콰니의 천둥 영혼 핵",
  "jiquanissoulcoreofthundering": "지콰니의 천둥 영혼 핵",
  "jiquanis-thesis": "지콰니의 명제",
  "jiquanisthesis": "지콰니의 명제",
  "opilotis-soul-core-of-assault": "오필로티의 맹공의 영혼 핵",
  "opilotissoulcoreofassault": "오필로티의 맹공의 영혼 핵",
  "quipolatls-thesis": "퀴폴라틀의 명제",
  "quipolatlsthesis": "퀴폴라틀의 명제",
  "raven-touched-shard": "큰까마귀의 손길에 닿은 파편",
  "raventouchedshard": "큰까마귀의 손길에 닿은 파편",
  "soul-core-of-atmohua": "앗모후아의 영혼 핵",
  "soulcoreofatmohua": "앗모후아의 영혼 핵",
  "soul-core-of-cholotl": "촐로틀의 영혼 핵",
  "soulcoreofcholotl": "촐로틀의 영혼 핵",
  "soul-core-of-quipolatl": "퀴폴라틀의 영혼 핵",
  "soulcoreofquipolatl": "퀴폴라틀의 영혼 핵",
  "soul-core-of-tzamoto": "자모토의 영혼 핵",
  "soulcoreoftzamoto": "자모토의 영혼 핵",
  "soul-core-of-xopec": "조펙의 영혼 핵",
  "soulcoreofxopec": "조펙의 영혼 핵",
  "soul-core-of-zalatl": "잘라틀의 영혼 핵",
  "soulcoreofzalatl": "잘라틀의 영혼 핵",
  "tacatis-soul-core-of-affliction": "타카티의 수난의 영혼 핵",
  "tacatissoulcoreofaffliction": "타카티의 수난의 영혼 핵",
  "tzamotos-soul-core-of-ferocity": "자모토의 흉포함의 영혼 핵",
  "tzamotossoulcoreofferocity": "자모토의 흉포함의 영혼 핵",
  "uromotis-soul-core-of-attenuation": "우로모티의 감쇠의 영혼 핵",
  "uromotissoulcoreofattenuation": "우로모티의 감쇠의 영혼 핵",
  "zalatls-soul-core-of-insulation": "잘라틀의 절연의 영혼 핵",
  "zalatlssoulcoreofinsulation": "잘라틀의 절연의 영혼 핵",
  "adept-rune": "숙달 룬",
  "adeptrune": "숙달 룬",
  "aldurs-legacy": "알두르의 유산",
  "aldurslegacy": "알두르의 유산",
  "ancient-rune-of-animosity": "적대감의 고대 룬",
  "ancientruneofanimosity": "적대감의 고대 룬",
  "ancient-rune-of-control": "통제의 고대 룬",
  "ancientruneofcontrol": "통제의 고대 룬",
  "ancient-rune-of-decay": "부패의 고대 룬",
  "ancientruneofdecay": "부패의 고대 룬",
  "ancient-rune-of-detonation": "기폭의 고대 룬",
  "ancientruneofdetonation": "기폭의 고대 룬",
  "ancient-rune-of-discovery": "발견의 고대 룬",
  "ancientruneofdiscovery": "발견의 고대 룬",
  "ancient-rune-of-dueling": "결투의 고대 룬",
  "ancientruneofdueling": "결투의 고대 룬",
  "ancient-rune-of-prowess": "기량의 고대 룬",
  "ancientruneofprowess": "기량의 고대 룬",
  "ancient-rune-of-retaliation": "보복의 고대 룬",
  "ancientruneofretaliation": "보복의 고대 룬",
  "ancient-rune-of-shattering": "산산조각의 고대 룬",
  "ancientruneofshattering": "산산조각의 고대 룬",
  "ancient-rune-of-splinters": "파편의 고대 룬",
  "ancientruneofsplinters": "파편의 고대 룬",
  "ancient-rune-of-the-horde": "떼의 고대 룬",
  "ancientruneofthehorde": "떼의 고대 룬",
  "ancient-rune-of-the-titan": "거신의 고대 룬",
  "ancientruneofthetitan": "거신의 고대 룬",
  "astrids-creativity": "아스트리드의 창의성",
  "astridscreativity": "아스트리드의 창의성",
  "betrayal-of-aldur": "알두르의 배신",
  "betrayalofaldur": "알두르의 배신",
  "body-rune": "육신 룬",
  "bodyrune": "육신 룬",
  "breath-of-aldur": "알두르의 숨결",
  "breathofaldur": "알두르의 숨결",
  "cadigans-epiphany": "캐디건의 통찰",
  "cadigansepiphany": "캐디건의 통찰",
  "ancient-rune-of-witchcraft": "마술의 고대 룬",
  "ancientruneofwitchcraft": "마술의 고대 룬",
  "countess-seskes-rune-of-archery": "세스케 백작 부인의 궁술의 룬",
  "countessseskesruneofarchery": "세스케 백작 부인의 궁술의 룬",
  "courtesan-mannans-rune-of-cruelty": "매춘부 마난의 잔혹의 룬",
  "courtesanmannansruneofcruelty": "매춘부 마난의 잔혹의 룬",
  "craiceanns-rune-of-recovery": "크라칸의 회복의 룬",
  "craiceannsruneofrecovery": "크라칸의 회복의 룬",
  "craiceanns-rune-of-warding": "크라칸의 수호의 룬",
  "craiceannsruneofwarding": "크라칸의 수호의 룬",
  "emergent-possibility": "발현된 가능성",
  "emergentpossibility": "발현된 가능성",
  "farruls-rune-of-the-chase": "페룰의 추격의 룬",
  "farrulsruneofthechase": "페룰의 추격의 룬",
  "farruls-rune-of-the-hunt": "페룰의 사냥의 룬",
  "farrulsruneofthehunt": "페룰의 사냥의 룬",
  "fenumus-rune-of-agony": "페누무스의 괴로움의 룬",
  "fenumusruneofagony": "페누무스의 괴로움의 룬",
  "fenumus-rune-of-draining": "페누무스의 고갈의 룬",
  "fenumusruneofdraining": "페누무스의 고갈의 룬",
  "fenumus-rune-of-spinning": "페누무스의 회전의 룬",
  "fenumusruneofspinning": "페누무스의 회전의 룬",
  "glacial-rune": "빙하 룬",
  "glacialrune": "빙하 룬",
  "greater-adept-rune": "상위 숙달 룬",
  "greateradeptrune": "상위 숙달 룬",
  "greater-desert-rune": "상위 사막 룬",
  "greaterdesertrune": "상위 사막 룬",
  "greater-inspiration-rune": "상위 영감 룬",
  "greaterinspirationrune": "상위 영감 룬",
  "greater-resolve-rune": "상위 투지 룬",
  "greaterresolverune": "상위 투지 룬",
  "greater-robust-rune": "상위 왕성 룬",
  "greaterrobustrune": "상위 왕성 룬",
  "greater-rune-of-leadership": "통솔의 상위 룬",
  "greaterruneofleadership": "통솔의 상위 룬",
  "greater-rune-of-nobility": "고결성의 상위 룬",
  "greaterruneofnobility": "고결성의 상위 룬",
  "greater-vision-rune": "상위 환영 룬",
  "greatervisionrune": "상위 환영 룬",
  "iron-rune": "철 룬",
  "ironrune": "철 룬",
  "kolrs-hunt": "콜르의 사냥",
  "kolrshunt": "콜르의 사냥",
  "lesser-desert-rune": "하위 사막 룬",
  "lesserdesertrune": "하위 사막 룬",
  "lesser-resolve-rune": "하위 투지 룬",
  "lesserresolverune": "하위 투지 룬",
  "masterwork-rune": "일품 룬",
  "masterworkrune": "일품 룬",
  "medveds-tending": "메드베드의 보살핌",
  "medvedstending": "메드베드의 보살핌",
  "perfect-body-rune": "완벽한 육신 룬",
  "perfectbodyrune": "완벽한 육신 룬",
  "perfect-desert-rune": "완벽한 사막 룬",
  "perfectdesertrune": "완벽한 사막 룬",
  "perfect-glacial-rune": "완벽한 빙하 룬",
  "perfectglacialrune": "완벽한 빙하 룬",
  "perfect-inspiration-rune": "완벽한 영감 룬",
  "perfectinspirationrune": "완벽한 영감 룬",
  "perfect-mind-rune": "완벽한 정신 룬",
  "perfectmindrune": "완벽한 정신 룬",
  "perfect-stone-rune": "완벽한 돌 룬",
  "perfectstonerune": "완벽한 돌 룬",
  "perfect-storm-rune": "완벽한 폭풍 룬",
  "perfectstormrune": "완벽한 폭풍 룬",
  "perfect-vision-rune": "완벽한 환영 룬",
  "perfectvisionrune": "완벽한 환영 룬",
  "resolve-rune": "투지 룬",
  "resolverune": "투지 룬",
  "robust-rune": "왕성한 룬",
  "robustrune": "왕성한 룬",
  "rune-of-acrobatics": "곡예의 룬",
  "runeofacrobatics": "곡예의 룬",
  "rune-of-confrontation": "대적의 룬",
  "runeofconfrontation": "대적의 룬",
  "rune-of-consistency": "일관성의 룬",
  "runeofconsistency": "일관성의 룬",
  "rune-of-foundations": "기초의 룬",
  "runeoffoundations": "기초의 룬",
  "rune-of-the-blossom": "만개의 룬",
  "runeoftheblossom": "만개의 룬",
  "saqawals-rune-of-erosion": "사카왈의 침식의 룬",
  "saqawalsruneoferosion": "사카왈의 침식의 룬",
  "saqawals-rune-of-the-sky": "사카왈의 하늘의 룬",
  "saqawalsruneofthesky": "사카왈의 하늘의 룬",
  "serles-triumph": "세를의 승리",
  "serlestriumph": "세를의 승리",
  "storm-rune": "폭풍 룬",
  "stormrune": "폭풍 룬",
  "thane-girts-rune-of-wildness": "테인 거트의 야생의 룬",
  "thanegirtsruneofwildness": "테인 거트의 야생의 룬",
  "thane-grannells-rune-of-mastery": "테인 그라넬의 숙련의 룬",
  "thanegrannellsruneofmastery": "테인 그라넬의 숙련의 룬",
  "thane-lelds-rune-of-spring": "테인 렐드의 봄의 룬",
  "thaneleldsruneofspring": "테인 렐드의 봄의 룬",
  "the-greatwolfs-rune-of-willpower": "위대한 늑대의 의지의 룬",
  "thegreatwolfsruneofwillpower": "위대한 늑대의 의지의 룬",
  "thruds-might": "스루드의 완력",
  "thrudsmight": "스루드의 완력",
  "uhtreds-sidereus": "우트레드의 성좌",
  "uhtredssidereus": "우트레드의 성좌",
  "voranas-carnage": "보라나의 학살",
  "voranascarnage": "보라나의 학살",
  "warding-rune-of-armature": "골조의 수호하는 룬",
  "wardingruneofarmature": "골조의 수호하는 룬",
  "warding-rune-of-courage": "용기의 수호하는 룬",
  "wardingruneofcourage": "용기의 수호하는 룬",
  "warding-rune-of-equinox": "지점의 수호하는 룬",
  "wardingruneofequinox": "지점의 수호하는 룬",
  "warding-rune-of-heart": "심장의 수호하는 룬",
  "wardingruneofheart": "심장의 수호하는 룬",
  "warding-rune-of-hollowing": "공동화의 수호하는 룬",
  "wardingruneofhollowing": "공동화의 수호하는 룬",
  "warding-rune-of-reinforcement": "보강의 수호하는 룬",
  "wardingruneofreinforcement": "보강의 수호하는 룬",
  "warding-rune-of-salvaging": "분해의 수호하는 룬",
  "wardingruneofsalvaging": "분해의 수호하는 룬",
  "warding-rune-of-stability": "안정성의 수호하는 룬",
  "wardingruneofstability": "안정성의 수호하는 룬",
  "charging-rune": "충전 룬",
  "chargingrune": "충전 룬",
  "desert-rune": "사막 룬",
  "desertrune": "사막 룬",
  "perfect-charging-rune": "완벽한 충전 룬",
  "perfectchargingrune": "완벽한 충전 룬",
  "emergent-instinct": "발현된 본능",
  "emergentinstinct": "발현된 본능",
  "emergent-protection": "발현된 보호",
  "emergentprotection": "발현된 보호",
  "emergent-vigour": "발현된 활력",
  "emergentvigour": "발현된 활력",
  "lesser-rebirth-rune": "하위 부활 룬",
  "lesserrebirthrune": "하위 부활 룬",
  "lesser-ward-rune": "하위 수호 룬",
  "lesserwardrune": "하위 수호 룬",
  "warding-rune-of-obsession": "집착의 수호하는 룬",
  "wardingruneofobsession": "집착의 수호하는 룬",
  "farruls-rune-of-grace": "페룰의 은총의 룬",
  "farrulsruneofgrace": "페룰의 은총의 룬",
  "greater-body-rune": "상위 육신 룬",
  "greaterbodyrune": "상위 육신 룬",
  "greater-charging-rune": "상위 충전 룬",
  "greaterchargingrune": "상위 충전 룬",
  "greater-glacial-rune": "상위 빙하 룬",
  "greaterglacialrune": "상위 빙하 룬",
  "greater-iron-rune": "상위 철 룬",
  "greaterironrune": "상위 철 룬",
  "greater-mind-rune": "상위 정신 룬",
  "greatermindrune": "상위 정신 룬",
  "greater-rebirth-rune": "상위 부활 룬",
  "greaterrebirthrune": "상위 부활 룬",
  "greater-rune-of-alacrity": "기민성의 상위 룬",
  "greaterruneofalacrity": "기민성의 상위 룬",
  "greater-rune-of-tithing": "십일조의 상위 룬",
  "greaterruneoftithing": "십일조의 상위 룬",
  "greater-stone-rune": "상위 돌 룬",
  "greaterstonerune": "상위 돌 룬",
  "greater-storm-rune": "상위 폭풍 룬",
  "greaterstormrune": "상위 폭풍 룬",
  "greater-ward-rune": "상위 수호 룬",
  "greaterwardrune": "상위 수호 룬",
  "hedgewitch-assandras-rune-of-wisdom": "산울마녀 아산드라의 지혜의 룬",
  "hedgewitchassandrasruneofwisdom": "산울마녀 아산드라의 지혜의 룬",
  "inspiration-rune": "영감 룬",
  "inspirationrune": "영감 룬",
  "ire-of-aldur": "알두르의 노여움",
  "ireofaldur": "알두르의 노여움",
  "katlas-gloom": "카틀라의 순흑",
  "katlasgloom": "카틀라의 순흑",
  "lady-hestras-rune-of-winter": "헤스트라 부인의 겨울의 룬",
  "ladyhestrasruneofwinter": "헤스트라 부인의 겨울의 룬",
  "lesser-adept-rune": "하위 숙달 룬",
  "lesseradeptrune": "하위 숙달 룬",
  "lesser-body-rune": "하위 육신 룬",
  "lesserbodyrune": "하위 육신 룬",
  "lesser-glacial-rune": "하위 빙하 룬",
  "lesserglacialrune": "하위 빙하 룬",
  "lesser-inspiration-rune": "하위 영감 룬",
  "lesserinspirationrune": "하위 영감 룬",
  "lesser-iron-rune": "하위 철 룬",
  "lesserironrune": "하위 철 룬",
  "lesser-mind-rune": "하위 정신 룬",
  "lessermindrune": "하위 정신 룬",
  "lesser-robust-rune": "하위 왕성 룬",
  "lesserrobustrune": "하위 왕성 룬",
  "lesser-storm-rune": "하위 폭풍 룬",
  "lesserstormrune": "하위 폭풍 룬",
  "mind-rune": "정신 룬",
  "mindrune": "정신 룬",
  "passion-of-aldur": "알두르의 열정",
  "passionofaldur": "알두르의 열정",
  "perfect-adept-rune": "완벽한 숙달 룬",
  "perfectadeptrune": "완벽한 숙달 룬",
  "perfect-iron-rune": "완벽한 철 룬",
  "perfectironrune": "완벽한 철 룬",
  "perfect-rebirth-rune": "완벽한 부활 룬",
  "perfectrebirthrune": "완벽한 부활 룬",
  "perfect-resolve-rune": "완벽한 투지 룬",
  "perfectresolverune": "완벽한 투지 룬",
  "perfect-robust-rune": "완벽한 왕성한 룬",
  "perfectrobustrune": "완벽한 왕성한 룬",
  "perfect-ward-rune": "완벽한 수호 룬",
  "perfectwardrune": "완벽한 수호 룬",
  "rune-of-accumulation": "축적의 룬",
  "runeofaccumulation": "축적의 룬",
  "rune-of-culmination": "고조의 룬",
  "runeofculmination": "고조의 룬",
  "rune-of-reach": "범위의 룬",
  "runeofreach": "범위의 룬",
  "rune-of-renown": "명성의 룬",
  "runeofrenown": "명성의 룬",
  "rune-of-the-hunt": "사냥의 룬",
  "runeofthehunt": "사냥의 룬",
  "rune-of-the-prism": "분광기의 룬",
  "runeoftheprism": "분광기의 룬",
  "rune-of-vitality": "활력의 룬",
  "runeofvitality": "활력의 룬",
  "saqawals-rune-of-memory": "사카왈의 기억의 룬",
  "saqawalsruneofmemory": "사카왈의 기억의 룬",
  "thane-myrks-rune-of-summer": "테인 머크의 여름의 룬",
  "thanemyrksruneofsummer": "테인 머크의 여름의 룬",
  "the-greatwolfs-rune-of-claws": "위대한 늑대의 발톱의 룬",
  "thegreatwolfsruneofclaws": "위대한 늑대의 발톱의 룬",
  "vision-rune": "환영 룬",
  "visionrune": "환영 룬",
  "warding-rune-of-annihilation": "전멸의 수호하는 룬",
  "wardingruneofannihilation": "전멸의 수호하는 룬",
  "warding-rune-of-bodyguards": "호위병의 수호하는 룬",
  "wardingruneofbodyguards": "호위병의 수호하는 룬",
  "warding-rune-of-desperation": "필사의 수호하는 룬",
  "wardingruneofdesperation": "필사의 수호하는 룬",
  "warding-rune-of-disintegration": "분해의 수호하는 룬",
  "wardingruneofdisintegration": "분해의 수호하는 룬",
  "warding-rune-of-glancing": "튕김의 수호하는 룬",
  "wardingruneofglancing": "튕김의 수호하는 룬",
  "warding-rune-of-nourishment": "자양분의 수호하는 룬",
  "wardingruneofnourishment": "자양분의 수호하는 룬",
  "warding-rune-of-protection": "보호의 수호하는 룬",
  "wardingruneofprotection": "보호의 수호하는 룬",
  "warding-rune-of-symbiosis": "공생의 수호하는 룬",
  "wardingruneofsymbiosis": "공생의 수호하는 룬",
  "ward-rune": "수호 룬",
  "wardrune": "수호 룬",
  "lesser-stone-rune": "하위 돌 룬",
  "lesserstonerune": "하위 돌 룬",
  "carved-cunning": "조각된 교활함",
  "carvedcunning": "조각된 교활함",
  "carved-majesty": "조각된 위엄",
  "carvedmajesty": "조각된 위엄",
  "carved-mischief": "조각된 장난기",
  "carvedmischief": "조각된 장난기",
  "carved-tenacity": "조각된 참을성",
  "carvedtenacity": "조각된 참을성",
  "cat-idol": "고양이 우상",
  "catidol": "고양이 우상",
  "bear-idol": "곰 우상",
  "bearidol": "곰 우상",
  "boar-idol": "멧돼지 우상",
  "boaridol": "멧돼지 우상",
  "idol-of-alira": "알리라의 우상",
  "idolofalira": "알리라의 우상",
  "idol-of-eeshta": "이쉬타의 우상",
  "idolofeeshta": "이쉬타의 우상",
  "idol-of-egrin": "에그린의 우상",
  "idolofegrin": "에그린의 우상",
  "idol-of-eramir": "에라미어의 우상",
  "idoloferamir": "에라미어의 우상",
  "idol-of-greust": "그루스트의 우상",
  "idolofgreust": "그루스트의 우상",
  "idol-of-maxarius": "막사리우스의 우상",
  "idolofmaxarius": "막사리우스의 우상",
  "idol-of-oak": "오크의 우상",
  "idolofoak": "오크의 우상",
  "idol-of-ralakesh": "랄라케쉬의 우상",
  "idolofralakesh": "랄라케쉬의 우상",
  "idol-of-the-martyr": "순교자의 우상",
  "idolofthemartyr": "순교자의 우상",
  "idol-of-the-sycophant": "아첨꾼의 우상",
  "idolofthesycophant": "아첨꾼의 우상",
  "idol-of-yeena": "이이나의 우상",
  "idolofyeena": "이이나의 우상",
  "owl-idol": "올빼미 우상",
  "owlidol": "올빼미 우상",
  "primate-idol": "영장류 우상",
  "primateidol": "영장류 우상",
  "stag-idol": "수사슴 우상",
  "stagidol": "수사슴 우상",
  "stoat-idol": "담비 우상",
  "stoatidol": "담비 우상",
  "wolf-idol": "늑대 우상",
  "wolfidol": "늑대 우상",
  "fox-idol": "여우 우상",
  "foxidol": "여우 우상",
  "hawk-idol": "매 우상",
  "hawkidol": "매 우상",
  "idol-of-grold": "그롤드의 우상",
  "idolofgrold": "그롤드의 우상",
  "idol-of-kraityn": "크레이틴의 우상",
  "idolofkraityn": "크레이틴의 우상",
  "idol-of-silk": "실크의 우상",
  "idolofsilk": "실크의 우상",
  "idol-of-sirrius": "시리우스의 우상",
  "idolofsirrius": "시리우스의 우상",
  "idol-of-the-pharisee": "바리새인의 우상",
  "idolofthepharisee": "바리새인의 우상",
  "idol-of-thruldana": "스룰다나의 우상",
  "idolofthruldana": "스룰다나의 우상",
  "ox-idol": "소 우상",
  "oxidol": "소 우상",
  "panther-idol": "흑표 우상",
  "pantheridol": "흑표 우상",
  "rabbit-idol": "토끼 우상",
  "rabbitidol": "토끼 우상",
  "snake-idol": "독사 우상",
  "snakeidol": "독사 우상",
  "altered-collarbone": "뒤바뀐 빗장뼈",
  "alteredcollarbone": "뒤바뀐 빗장뼈",
  "amanamus-gaze": "아마나무의 응시",
  "amanamusgaze": "아마나무의 응시",
  "ancient-collarbone": "고대 빗장뼈",
  "ancientcollarbone": "고대 빗장뼈",
  "ancient-jawbone": "고대 턱뼈",
  "ancientjawbone": "고대 턱뼈",
  "ancient-rib": "고대 갈비뼈",
  "ancientrib": "고대 갈비뼈",
  "gnawed-jawbone": "갉힌 턱뼈",
  "gnawedjawbone": "갉힌 턱뼈",
  "kurgals-gaze": "쿠르갈의 응시",
  "kurgalsgaze": "쿠르갈의 응시",
  "preserved-cranium": "보존된 두개골",
  "preservedcranium": "보존된 두개골",
  "preserved-jawbone": "보존된 턱뼈",
  "preservedjawbone": "보존된 턱뼈",
  "tecrods-gaze": "테크로드의 응시",
  "tecrodsgaze": "테크로드의 응시",
  "gnawed-collarbone": "갉힌 빗장뼈",
  "gnawedcollarbone": "갉힌 빗장뼈",
  "gnawed-rib": "갉힌 갈비뼈",
  "gnawedrib": "갉힌 갈비뼈",
  "preserved-collarbone": "보존된 빗장뼈",
  "preservedcollarbone": "보존된 빗장뼈",
  "preserved-rib": "보존된 갈비뼈",
  "preservedrib": "보존된 갈비뼈",
  "ulamans-gaze": "울라만의 응시",
  "ulamansgaze": "울라만의 응시",
  "ancient-concentrated-liquid-isolation": "고대 농축된 액체 고립",
  "ancientconcentratedliquidisolation": "고대 농축된 액체 고립",
  "ancient-concentrated-liquid-suffering": "고대 농축된 액체 고통",
  "ancientconcentratedliquidsuffering": "고대 농축된 액체 고통",
  "ancient-diluted-liquid-greed": "고대 희석된 액체 탐욕",
  "ancientdilutedliquidgreed": "고대 희석된 액체 탐욕",
  "ancient-diluted-liquid-ire": "고대 희석된 액체 진노",
  "ancientdilutedliquidire": "고대 희석된 액체 진노",
  "ancient-liquid-disgust": "고대 액체 혐오",
  "ancientliquiddisgust": "고대 액체 혐오",
  "ancient-liquid-envy": "고대 액체 선망",
  "ancientliquidenvy": "고대 액체 선망",
  "ancient-liquid-paranoia": "고대 액체 집착",
  "ancientliquidparanoia": "고대 액체 집착",
  "ancient-potent-liquid-contempt": "고대 위력적인 액체 경멸",
  "ancientpotentliquidcontempt": "고대 위력적인 액체 경멸",
  "ancient-potent-liquid-ferocity": "고대 위력적인 액체 흉포함",
  "ancientpotentliquidferocity": "고대 위력적인 액체 흉포함",
  "ancient-concentrated-liquid-fear": "고대 농축된 액체 두려움",
  "ancientconcentratedliquidfear": "고대 농축된 액체 두려움",
  "ancient-liquid-despair": "고대 액체 절망",
  "ancientliquiddespair": "고대 액체 절망",
  "ancient-potent-liquid-melancholy": "고대 위력적인 액체 우울",
  "ancientpotentliquidmelancholy": "고대 위력적인 액체 우울",
  "concentrated-liquid-isolation": "농축된 액체 고립",
  "concentratedliquidisolation": "농축된 액체 고립",
  "concentrated-liquid-suffering": "농축된 액체 고통",
  "concentratedliquidsuffering": "농축된 액체 고통",
  "diluted-liquid-ire": "희석된 액체 진노",
  "dilutedliquidire": "희석된 액체 진노",
  "liquid-despair": "액체 절망",
  "liquiddespair": "액체 절망",
  "liquid-envy": "액체 선망",
  "liquidenvy": "액체 선망",
  "liquid-paranoia": "액체 집착",
  "liquidparanoia": "액체 집착",
  "potent-liquid-ferocity": "위력적인 액체 흉포함",
  "potentliquidferocity": "위력적인 액체 흉포함",
  "concentrated-liquid-fear": "농축된 액체 두려움",
  "concentratedliquidfear": "농축된 액체 두려움",
  "diluted-liquid-greed": "희석된 액체 탐욕",
  "dilutedliquidgreed": "희석된 액체 탐욕",
  "diluted-liquid-guilt": "희석된 액체 죄책감",
  "dilutedliquidguilt": "희석된 액체 죄책감",
  "ancient-diluted-liquid-guilt": "고대 희석된 액체 죄책감",
  "ancientdilutedliquidguilt": "고대 희석된 액체 죄책감",
  "liquid-disgust": "액체 혐오",
  "liquiddisgust": "액체 혐오",
  "potent-liquid-contempt": "위력적인 액체 경멸",
  "potentliquidcontempt": "위력적인 액체 경멸",
  "potent-liquid-melancholy": "위력적인 액체 우울",
  "potentliquidmelancholy": "위력적인 액체 우울",
  "adaptive-catalyst": "적응형 기폭제",
  "adaptivecatalyst": "적응형 기폭제",
  "breach-splinter": "균열 파편",
  "breachsplinter": "균열 파편",
  "breachstone": "균열석",
  "carapace-catalyst": "갑각 기폭제",
  "carapacecatalyst": "갑각 기폭제",
  "eshs-catalyst": "에쉬의 기폭제",
  "eshscatalyst": "에쉬의 기폭제",
  "flesh-catalyst": "육체 기폭제",
  "fleshcatalyst": "육체 기폭제",
  "necrotic-catalyst": "괴사의 기폭제",
  "necroticcatalyst": "괴사의 기폭제",
  "reaver-catalyst": "강탈자 기폭제",
  "reavercatalyst": "강탈자 기폭제",
  "refined-carapace-catalyst": "제련된 갑각 기폭제",
  "refinedcarapacecatalyst": "제련된 갑각 기폭제",
  "refined-chayulas-catalyst": "제련된 차율라의 기폭제",
  "refinedchayulascatalyst": "제련된 차율라의 기폭제",
  "refined-necrotic-catalyst": "제련된 괴사의 기폭제",
  "refinednecroticcatalyst": "제련된 괴사의 기폭제",
  "refined-skittering-catalyst": "제련된 달리는 기폭제",
  "refinedskitteringcatalyst": "제련된 달리는 기폭제",
  "refined-tuls-catalyst": "제련된 툴의 기폭제",
  "refinedtulscatalyst": "제련된 툴의 기폭제",
  "sibilant-catalyst": "쇳소리 기폭제",
  "sibilantcatalyst": "쇳소리 기폭제",
  "uul-netols-catalyst": "울네톨의 기폭제",
  "uulnetolscatalyst": "울네톨의 기폭제",
  "xophs-catalyst": "조프의 기폭제",
  "xophscatalyst": "조프의 기폭제",
  "chayulas-catalyst": "차율라의 기폭제",
  "chayulascatalyst": "차율라의 기폭제",
  "neural-catalyst": "신경 기폭제",
  "neuralcatalyst": "신경 기폭제",
  "refined-adaptive-catalyst": "제련된 적응형 기폭제",
  "refinedadaptivecatalyst": "제련된 적응형 기폭제",
  "refined-eshs-catalyst": "제련된 에쉬의 기폭제",
  "refinedeshscatalyst": "제련된 에쉬의 기폭제",
  "refined-flesh-catalyst": "제련된 육체 기폭제",
  "refinedfleshcatalyst": "제련된 육체 기폭제",
  "refined-neural-catalyst": "제련된 신경 기폭제",
  "refinedneuralcatalyst": "제련된 신경 기폭제",
  "refined-reaver-catalyst": "제련된 강탈자 기폭제",
  "refinedreavercatalyst": "제련된 강탈자 기폭제",
  "refined-sibilant-catalyst": "제련된 쇳소리 기폭제",
  "refinedsibilantcatalyst": "제련된 쇳소리 기폭제",
  "refined-uul-netols-catalyst": "제련된 울네톨의 기폭제",
  "refineduulnetolscatalyst": "제련된 울네톨의 기폭제",
  "refined-xophs-catalyst": "제련된 조프의 기폭제",
  "refinedxophscatalyst": "제련된 조프의 기폭제",
  "skittering-catalyst": "달리는 기폭제",
  "skitteringcatalyst": "달리는 기폭제",
  "tuls-catalyst": "툴의 기폭제",
  "tulscatalyst": "툴의 기폭제",
  "blazing-flux": "맹렬한 유동체",
  "blazingflux": "맹렬한 유동체",
  "chilling-flux": "오싹한 유동체",
  "chillingflux": "오싹한 유동체",
  "crackling-flux": "치직대는 유동체",
  "cracklingflux": "치직대는 유동체",
  "perfect-flux": "완벽한 유동체",
  "perfectflux": "완벽한 유동체",
  "thaumaturgic-flux-13": "마석학 유동체 (13레벨)",
  "thaumaturgic-flux-level-13": "마석학 유동체 (13레벨)",
  "thaumaturgicfluxlevel13": "마석학 유동체 (13레벨)",
  "thaumaturgic-flux-15": "마석학 유동체 (15레벨)",
  "thaumaturgic-flux-level-15": "마석학 유동체 (15레벨)",
  "thaumaturgicfluxlevel15": "마석학 유동체 (15레벨)",
  "thaumaturgic-flux-16": "마석학 유동체 (16레벨)",
  "thaumaturgic-flux-level-16": "마석학 유동체 (16레벨)",
  "thaumaturgicfluxlevel16": "마석학 유동체 (16레벨)",
  "thaumaturgic-flux-17": "마석학 유동체 (17레벨)",
  "thaumaturgic-flux-level-17": "마석학 유동체 (17레벨)",
  "thaumaturgicfluxlevel17": "마석학 유동체 (17레벨)",
  "thaumaturgic-flux-18": "마석학 유동체 (18레벨)",
  "thaumaturgic-flux-level-18": "마석학 유동체 (18레벨)",
  "thaumaturgicfluxlevel18": "마석학 유동체 (18레벨)",
  "thaumaturgic-flux-19": "마석학 유동체 (19레벨)",
  "thaumaturgic-flux-level-19": "마석학 유동체 (19레벨)",
  "thaumaturgicfluxlevel19": "마석학 유동체 (19레벨)",
  "thaumaturgic-flux-20": "마석학 유동체 (20레벨)",
  "thaumaturgic-flux-level-20": "마석학 유동체 (20레벨)",
  "thaumaturgicfluxlevel20": "마석학 유동체 (20레벨)",
  "void-flux": "공허 유동체",
  "voidflux": "공허 유동체",
  "expedition-logbook": "탐험 일지",
  "expeditionlogbook": "탐험 일지",
  "medveds-saga": "메드베드의 영웅담",
  "medvedssaga": "메드베드의 영웅담",
  "olroths-saga": "올로스의 영웅담",
  "olrothssaga": "올로스의 영웅담",
  "thaumaturgic-flux-14": "마석학 유동체 (14레벨)",
  "thaumaturgic-flux-level-14": "마석학 유동체 (14레벨)",
  "thaumaturgicfluxlevel14": "마석학 유동체 (14레벨)",
  "uhtreds-saga": "우트레드의 영웅담",
  "uhtredssaga": "우트레드의 영웅담",
  "voranas-saga": "보라나의 영웅담",
  "voranassaga": "보라나의 영웅담",
  "adaptive-alloy": "적응형 합금",
  "adaptivealloy": "적응형 합금",
  "celestial-alloy": "천공의 합금",
  "celestialalloy": "천공의 합금",
  "expansive-alloy": "팽창하는 합금",
  "expansivealloy": "팽창하는 합금",
  "liquid-verisium": "액체 베리시움",
  "liquidverisium": "액체 베리시움",
  "protective-alloy": "보호의 합금",
  "protectivealloy": "보호의 합금",
  "runic-alloy": "룬 합금",
  "runicalloy": "룬 합금",
  "sovereign-alloy": "군왕의 합금",
  "sovereignalloy": "군왕의 합금",
  "swift-alloy": "재빠른 합금",
  "swiftalloy": "재빠른 합금",
  "the-runefathers-alloy": "룬 아버지의 합금",
  "therunefathersalloy": "룬 아버지의 합금",
  "transcendent-alloy": "초월의 합금",
  "transcendentalloy": "초월의 합금",
  "venerable-starlit-ore": "덕망 있는 별빛 광석",
  "venerablestarlitore": "덕망 있는 별빛 광석",
  "veridical-starlit-ore": "진실한 별빛 광석",
  "veridicalstarlitore": "진실한 별빛 광석",
  "verisium": "베리시움",
  "cyclonic-alloy": "회오리바람 합금",
  "cyclonicalloy": "회오리바람 합금",
  "revered-starlit-ore": "존경받는 별빛 광석",
  "reveredstarlitore": "존경받는 별빛 광석",
  "exceptional-verisium": "특출난 베리시움",
  "exceptionalverisium": "특출난 베리시움",
  "medveds-crest-of-the-circle": "메드베드의 원 문양",
  "medvedscrestofthecircle": "메드베드의 원 문양",
  "mystic-alloy": "신비한 합금",
  "mysticalloy": "신비한 합금",
  "olroths-crest-of-the-sun": "올로스의 태양 문양",
  "olrothscrestofthesun": "올로스의 태양 문양",
  "prismatic-alloy": "분광 합금",
  "prismaticalloy": "분광 합금",
  "the-runebinders-alloy": "룬 결속사의 합금",
  "therunebindersalloy": "룬 결속사의 합금",
  "uhtreds-crest-of-the-chalice": "우트레드의 성배 문양",
  "uhtredscrestofthechalice": "우트레드의 성배 문양",
  "voranas-crest-of-the-scythe": "보라나의 낫 문양",
  "voranascrestofthescythe": "보라나의 낫 문양",
  "warding-starlit-ore": "수호하는 별빛 광석",
  "wardingstarlitore": "수호하는 별빛 광석"
};
